language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

script:
  - mvn clean install -DskipIT=false
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
